- name: "Create .kube directory for {{ ansible_ssh_user }}"
  file:
    path: "/home/{{ ansible_ssh_user }}/.kube"
    state: directory
    mode: 0700
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: "Setup kubeconfig for {{ ansible_ssh_user }}"
  become: true
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_ssh_user }}/.kube/config"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0600

- name: Replace host IP with load balancer in kubeconfig
  replace:
    path: "/home/{{ ansible_ssh_user }}/.kube/config"
    regexp: "{{ \"ip\" }}"
    replace: "{{ apiserver_loadbalancer_domain_name }}"
